<?php
/**
 *前端返回状态码
 *
 */

return [

    "params_error"=>[
        "code"=>1001,
        "msg"=>"请求参数不符合规则!"
    ],
    "login_success"=>[
        "code"=>200,
        "msg"=>"登陆成功!"
    ],
    "created_user_success"=>[
        "code"=>200,
        "msg"=>"创建成功!"
    ],
    "created_user_error"=>[
        "code"=>1002,
        "msg"=>"创建用户失败!"
    ],
    "add_live_success"=>[
        "code"=>200,
        "msg"=>"新增频道成功!"
    ],
    "add_live_error"=>[
        "code"=>1003,
        "msg"=>"新增频道失败!"
    ],
    "live_url_info"=>[
    "code"=>200,
    "msg"=>"Success!"
    ],
    "live_url_query_error"=>[
        "code"=>1004,
        "msg"=>"查询条件不能为空!"
    ],
    "login_err_not_user"=>[
        "code"=>205,
        "msg"=>"用户不存在!"
    ],
    "login_err_pwd"=>[
        "code"=>205,
        "msg"=>"密码错误!"
    ],
    "change_user_pwd_success"=>[
        "code"=>200,
        "msg"=>"密码更新成功!"
    ],
    "change_user_pwd_error"=>[
        "code"=>1005,
        "msg"=>"密码更新失败!"
    ],
    "change_liveinfo_success"=>[
        "code"=>200,
        "msg"=>"频道信息更新成功!"
    ],
    "change_liveinfo_error"=>[
        "code"=>1006,
        "msg"=>"频道信息更新失败!"
    ],
    "del_liveinfo_error"=>[
        "code"=>1007,
        "msg"=>"删除频道信息失败!"
    ],
    "del_liveinfo_success"=>[
        "code"=>200,
        "msg"=>"删除频道信息成功!"
    ]
];